### PR TITLE
ansible playbook provisioning

### PR DESCRIPTION
**Pull request by krageon**
For this to entirely work as expected, the zer.ooo service needs to:
- Generate it's own keys when necessary (not currently present)
- Register itself with a central node (eg https://zer.ooo/)

### CODE REVIEW

**Comment by EaterOfCode** [comment]
Did you test this?

**Comment by krageon** [comment]
I will, just as soon as I get vagrant working

**Comment by krageon** [comment]
I did test this and it works. The only thing that still doesn't work is the nodejs server instance (ha-ha), because I need to rewrite that to python and make it generate it's own keys if it doesn't have them.

**Comment by nienkedekker** [comment]
its*

**Comment by krageon** [comment]
I have brought shame to my family.

**Pull request merged**
